### ISSUE TITLE
without html to look at the css can be confusing

### ISSUE THREAD

**Issue by dylan-k** [mattharrison/epub-css-starter-kit#1]
Was this css built without any html to go with it? There are a number of styles here that would be a lot easier to understand with HTML to go with it for context. I'd be willing to help create an example epub for this, to help others, but some of these are confusing to me.

**Comment by mattharrison** [comment]
Hi Dylan-

There are a few ways to get examples for it. The rst2epub2 project has a sample book that will show some of the html. My recent book, Ebook Formatting: KF8, Mobi & EPUB, is basically a self-documenting ebook that contains source for html examples of the CSS. I should probably update the README to indicate this

0 - http://www.amazon.com/Ebook-Formatting-Mobi-EPUB-ebook/dp/B00BWQXHU6
